parameters:

services:
    qurep_api.route_analyzer:
        class: Solazs\QuReP\ApiBundle\Services\RouteAnalyzer
    qurep_api.data_handler:
        class: Solazs\QuReP\ApiBundle\Services\DataHandler
        arguments: [ "@doctrine.orm.entity_manager", "@qurep_api.entity_form_builder" ]
    qurep_api.exception_listener:
        class: Solazs\QuReP\ApiBundle\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 200 }
    qurep_api.entity_form_builder:
        class: Solazs\QuReP\ApiBundle\Services\EntityFormBuilder
        arguments: [ "@form.factory" ]
        lazy: true